# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c21d3f526cdb5dffdccdaf4aac7c784c7926b7dfbc3d876002620f4265277df83467c534a97baa35a2bd4780f4798f78b6990edd7ab02bade47d2a9eaea3e8e0

test:
  secret_key_base: 48df0876f22b5d6b52d2d017051b5b126c3fa24c94c39db63c5c5113797cda9fbedc7b5b19c6ee2f45a78c4647242870367553d605a721d596f281d0f6f449df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
